favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0
  brandStrength: 0.807049
  lightness: 1
  brandColors:
    - '#C8B998'
    - '#E3E1D4'
    - '#8F7F65'
    - '#1D1210'
    - '#5D4E39'
  rhythmicContrast: 0.9050179
typography_spectrum: 0.2120669
layout_spectrum: 0.7580644
cta:
  bucket: null
  version: null
  domain: null
name: The Blackbird Company
